5 Requests made to 38840 and failed
Traceback (most recent call last):
  File "C:\Users\W\Downloads\VimmsDownloader\script.py", line 558, in <module>
    main()
  File "C:\Users\W\Downloads\VimmsDownloader\script.py", line 554, in main
    run_selected_program(config)
  File "C:\Users\W\Downloads\VimmsDownloader\script.py", line 543, in run_selected_program
    download_bulk_roms(config, user_selected_bulk)
  File "C:\Users\W\Downloads\VimmsDownloader\script.py", line 520, in download_bulk_roms
    extract_and_delete_search_results(section.Path,download_name)
  File "C:\Users\W\Downloads\VimmsDownloader\script.py", line 495, in extract_and_delete_search_results
    extract_file(path, download)
  File "C:\Users\W\Downloads\VimmsDownloader\script.py", line 418, in extract_file
    file_name: str = str(base_filename[0][0])
IndexError: list index out of range