Traceback (most recent call last):
  File "/app/main.py", line 253, in main
    for comment in comment_stream:
  File "/app/.heroku/python/lib/python3.9/site-packages/praw/models/util.py", line 188, in stream_generator
    for item in reversed(list(function(limit=limit, **function_kwargs))):
  File "/app/.heroku/python/lib/python3.9/site-packages/praw/models/listing/generator.py", line 63, in __next__
    self._next_batch()
  File "/app/.heroku/python/lib/python3.9/site-packages/praw/models/listing/generator.py", line 73, in _next_batch
    self._listing = self._reddit.get(self.url, params=self.params)
  File "/app/.heroku/python/lib/python3.9/site-packages/praw/reddit.py", line 573, in get
    return self._objectify_request(method="GET", params=params, path=path)
  File "/app/.heroku/python/lib/python3.9/site-packages/praw/reddit.py", line 674, in _objectify_request
    self.request(
  File "/app/.heroku/python/lib/python3.9/site-packages/praw/reddit.py", line 856, in request
    return self._core.request(
  File "/app/.heroku/python/lib/python3.9/site-packages/prawcore/sessions.py", line 330, in request
    return self._request_with_retries(
  File "/app/.heroku/python/lib/python3.9/site-packages/prawcore/sessions.py", line 253, in _request_with_retries
    return self._do_retry(
  File "/app/.heroku/python/lib/python3.9/site-packages/prawcore/sessions.py", line 162, in _do_retry
    return self._request_with_retries(
  File "/app/.heroku/python/lib/python3.9/site-packages/prawcore/sessions.py", line 253, in _request_with_retries
    return self._do_retry(
  File "/app/.heroku/python/lib/python3.9/site-packages/prawcore/sessions.py", line 162, in _do_retry
    return self._request_with_retries(
  File "/app/.heroku/python/lib/python3.9/site-packages/prawcore/sessions.py", line 266, in _request_with_retries
    raise self.STATUS_EXCEPTIONS[response.status_code](response)
prawcore.exceptions.ServerError: received 502 HTTP response
