# bot.py

app = Client(
    "control_bot",
    api_id=API_ID, api_hash=API_HASH,
    bot_token=BOT_TOKEN,
    plugins=dict(root="admin")
)

userbot_app = Client(
    "userbot",
    api_id=API_ID, api_hash=API_HASH,
    plugins=dict(root="userbot")
)

if __name__ == "__main__":
   
    userbot_app.start()
    app.start()

    print("====================================")
    print("          Bot started")
    print("====================================")

    idle()

    app.stop()
    userbot_app.stop()

# admin/create_rule.py
import bot

@Client.on_message(filters.regex('Create rule') & auth_filter)
async def new_rule_donars(_, message):
    await message.reply_text("Loading channels âŒ›")
    donars = await get_readable_channels(bot.userbot_app) #
	print(donars)

async def get_readable_channels(app):
    raws = app.get_dialogs(
        limit=100,
    )

    channels = []

    async for channel in raws: # <---------- ConnectionError: Client has not been started yet
        if channel.chat.type == ChatType.CHANNEL:
            channels.append({
                "id": channel.chat.id,
                "name": channel.chat.title
            })

    return channels

# looks like the import bot statement cause to run the bot.py module again, so the userbot_app attribute is not what I expect.
    