Traceback (most recent call last):
  File "main.py", line 57, in wrapper
    job_func(*args, **kwargs)
  File "main.py", line 91, in comment_listener
    database_manager.load_comment(comment, db_conn)
  File "/root/Fallout76MarketplaceKarmaBot/database_manager.py", line 163, in load_comment
    process_command_non_mod_user(comment, db_conn)
  File "/root/Fallout76MarketplaceKarmaBot/database_manager.py", line 135, in process_command_non_mod_user
    output = karma_plus_command_non_mod_users(comment, db_conn)
  File "/root/Fallout76MarketplaceKarmaBot/database_manager.py", line 88, in karma_plus_command_non_mod_users
    conv_check_result = conversation_checks.checks_for_karma_command(comment)
  File "/root/Fallout76MarketplaceKarmaBot/conversation_checks.py", line 66, in checks_for_karma_command
    if flair_functions.is_mod_or_courier(user):
  File "/root/Fallout76MarketplaceKarmaBot/flair_functions.py", line 23, in is_mod_or_courier
    moderators_list = fallout76marketplace.moderator()
  File "/root/Fallout76MarketplaceKarmaBot/venv/lib/python3.8/site-packages/praw/models/reddit/subreddit.py", line 2960, in __call__
    return self.subreddit._reddit.get(url, params=params)
  File "/root/Fallout76MarketplaceKarmaBot/venv/lib/python3.8/site-packages/praw/reddit.py", line 595, in get
    return self._objectify_request(method="GET", params=params, path=path)
  File "/root/Fallout76MarketplaceKarmaBot/venv/lib/python3.8/site-packages/praw/reddit.py", line 696, in _objectify_request
    self.request(
  File "/root/Fallout76MarketplaceKarmaBot/venv/lib/python3.8/site-packages/praw/reddit.py", line 885, in request
    return self._core.request(
  File "/root/Fallout76MarketplaceKarmaBot/venv/lib/python3.8/site-packages/prawcore/sessions.py", line 330, in request
    return self._request_with_retries(
  File "/root/Fallout76MarketplaceKarmaBot/venv/lib/python3.8/site-packages/prawcore/sessions.py", line 228, in _request_with_retries
    response, saved_exception = self._make_request(
  File "/root/Fallout76MarketplaceKarmaBot/venv/lib/python3.8/site-packages/prawcore/sessions.py", line 185, in _make_request
    response = self._rate_limiter.call(
  File "/root/Fallout76MarketplaceKarmaBot/venv/lib/python3.8/site-packages/prawcore/rate_limit.py", line 33, in call
    kwargs["headers"] = set_header_callback()
  File "/root/Fallout76MarketplaceKarmaBot/venv/lib/python3.8/site-packages/prawcore/sessions.py", line 283, in _set_header_callback
    self._authorizer.refresh()
  File "/root/Fallout76MarketplaceKarmaBot/venv/lib/python3.8/site-packages/prawcore/auth.py", line 425, in refresh
    self._request_token(
  File "/root/Fallout76MarketplaceKarmaBot/venv/lib/python3.8/site-packages/prawcore/auth.py", line 155, in _request_token
    response = self._authenticator._post(url, **data)
  File "/root/Fallout76MarketplaceKarmaBot/venv/lib/python3.8/site-packages/prawcore/auth.py", line 38, in _post
    raise ResponseException(response)
prawcore.exceptions.ResponseException: received 502 HTTP response
